# Generated by Django 4.2.27 on 2026-02-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team13', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprompt',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prompt',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
