# Generated by Django 4.2.27 on 2026-02-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2', '0002_add_user_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
