# Generated by Django 4.2.27 on 2026-02-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2', '0003_remove_userdetails_user_userdetails_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='lesson',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='user_details_set', to='team2.lesson'),
        ),
    ]
