# Generated by Django 4.2.27 on 2026-02-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2', '0004_remove_userdetails_lesson_userdetails_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='videofiles',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
