# Generated by Django 4.2.27 on 2026-02-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team2', '0006_lesson_creator'),
        ('team2', '0007_question_lessonview_answer_and_more'),
    ]

    operations = [
    ]
